### ISSUE TITLE
Subtotal and total Doesn't Complete

### ISSUE THREAD

**Issue by theneonstark** [theneonstark/stark_store#6]
# Problem
### I fetch every details of product but when I total the price of product I doesn't because in php we have array_sum() method and the data we have that the string so solve the issue ASAP @theTarunsagwal @PunitDev0
https://github.com/theneonstark/stark_store/blob/0697a7a72e9112b00a7c84aab2603df6f2567693/order_details.php#L455

**Comment by PunitDev0** [comment]
Convert string into float then use array sum array_map(floatval,prices).

**Comment by theneonstark** [comment]
Do it 😁> Convert string into float then use array sum array_map(floatval,prices).
